# Site settings
title: The road less traveled by
description: Yikai photography
baseurl: "/lens-page" # the subpath of your site, e.g. /blog
url: "https://davidykzhao.github.io" # the base hostname & protocol for your site
author: Yikai Zhao

# Collection settings
collections:
  photos:

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/DavidykZhao
gitlab_url: 
googleplus_url: 
instagram_url:
linkedin_url: https://www.linkedin.com/in/yikaizhao/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/zdw2126062

# Build settings
markdown: kramdown
