# Site settings
title: My road, my steps
description: Yikai's photography works.
baseurl: "/lens-page" # the subpath of your site, e.g. /blog
url: "https://davidykzhao.github.io" # the base hostname & protocol for your site
author: Yikai Zhao

# Collection settings
collections:
  photos:

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/DavidykZhao
gitlab_url: 
googleplus_url: 
instagram_url:
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: https://twitter.com/zdw2126062

# Build settings
markdown: kramdown
